export const CONTENT_STATUSES = {
  DRAFT: "DRAFT",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  SCHEDULED: "SCHEDULED",
  PUBLISHED: "PUBLISHED",
  REJECTED: "REJECTED",
};

export const CONTENT_TYPES = ["Reel", "Post", "Lecture video", "Others"];

export const PLATFORMS = ["Instagram", "YouTube", "LinkedIn", "Facebook"];

export const PRIORITY_LEVELS = ["LOW", "MEDIUM", "HIGH", "URGENT"];

export const USER_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  CONTENT_MANAGER: "CONTENT_MANAGER",
  CONTRIBUTOR: "CONTRIBUTOR",
};

// Valid status transitions (mirrors backend)
export const STATUS_TRANSITIONS = {
  DRAFT: ["ASSIGNED"],
  ASSIGNED: ["IN_PROGRESS", "DRAFT"],
  IN_PROGRESS: ["COMPLETED", "SUBMITTED", "ASSIGNED"],
  COMPLETED: ["APPROVED", "REJECTED", "ASSIGNED"],
  SUBMITTED: ["APPROVED", "REJECTED", "ASSIGNED"],
  REJECTED: ["IN_PROGRESS", "ASSIGNED"],
  APPROVED: ["SCHEDULED", "PUBLISHED", "ASSIGNED"],
  SCHEDULED: ["PUBLISHED", "ASSIGNED", "DRAFT"],
  PUBLISHED: ["ASSIGNED", "DRAFT"],
};

export const API_BASE_URL = import.meta.env.VITE_API_URL || "/api";

export const PAGINATION_DEFAULT = {
  page: 1,
  limit: 20,
};
